import Head from "next/head";
import Image from "next/image";
import favicon from "../public/favicon.ico";

import HomePage from "@pages/home";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Portfolio-Priska</title>
        <meta name="description" content="Generated by create next app" />
       <link rel="favicon" href="../public/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
};

export default Home;
