import Head from 'next/head';
import Image from 'next/image';

import HomePage from "@pages/home";


const Home = () => {
  return (
    <div className="">
      <Head>
        <title>Portfolio - Priska</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <HomePage />
    </div>
  )
}

export default Home;